name: "Increment version"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[update version]')"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.PAT_TOKEN }}
    - name: Setup git user
      run: |
         git config --global user.email "action@github.com"
         git config --global user.name "GitHub Action"
    - name: Update Version
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
         export VERSION=`grep Bundle-Version org.jd.ide.eclipse.plugin/META-INF/MANIFEST.MF | cut -d: -f2 | xargs`
         export MAJOR=`echo $VERSION | cut -d. -f1`
         export MINOR=`echo $VERSION | cut -d. -f2`
         export PATCH=`echo $VERSION | cut -d. -f3`
         export NEW_PATCH=`expr $PATCH + 1`
         export NEW_VERSION=$MAJOR.$MINOR.$NEW_PATCH
         chmod u+x ./update-version.sh
         ./update-version.sh $NEW_VERSION
         git commit -a -m "[update version] $VERSION -> $NEW_VERSION"
         git push
         git tag -a $NEW_VERSION -m "$NEW_VERSION"
         git push origin $NEW_VERSION
       